package model.pojo;
// Generated 22 juin 2016 15:27:10 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Absence generated by hbm2java
 */
@Entity
@Table(name="absence"
    ,schema="dbo"
    ,catalog="Application_GRH"
)
public class Absence  implements java.io.Serializable {


     private int idAbsence;
     private Personnel personnel;
     private Integer nombreJourAbsence;

    public Absence() {
    }

	
    public Absence(int idAbsence, Personnel personnel) {
        this.idAbsence = idAbsence;
        this.personnel = personnel;
    }
    public Absence(int idAbsence, Personnel personnel, Integer nombreJourAbsence) {
       this.idAbsence = idAbsence;
       this.personnel = personnel;
       this.nombreJourAbsence = nombreJourAbsence;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.AUTO)


    
    @Column(name="id_absence", unique=true, nullable=false)
    public int getIdAbsence() {
        return this.idAbsence;
    }
    
    public void setIdAbsence(int idAbsence) {
        this.idAbsence = idAbsence;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_personnel", nullable=false)
    public Personnel getPersonnel() {
        return this.personnel;
    }
    
    public void setPersonnel(Personnel personnel) {
        this.personnel = personnel;
    }

    
    @Column(name="nombre_jour_absence")
    public Integer getNombreJourAbsence() {
        return this.nombreJourAbsence;
    }
    
    public void setNombreJourAbsence(Integer nombreJourAbsence) {
        this.nombreJourAbsence = nombreJourAbsence;
    }




}


