package model.pojo;
// Generated 22 juin 2016 15:27:10 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Candidat generated by hbm2java
 */
@Entity
@Table(name="candidat"
    ,schema="dbo"
    ,catalog="Application_GRH"
)
public class Candidat  implements java.io.Serializable {


     private int idCandidat;
     private String nomPrenomCandidat;
     private String cinCandidat;
     private Integer numTelCandidat;
     private String adresseCandidat;
     private Date dateNaissanceCandidat;
     private String cv;
     private String motivation;

    public Candidat() {
    }

	
    public Candidat(int idCandidat) {
        this.idCandidat = idCandidat;
    }
    public Candidat(int idCandidat, String nomPrenomCandidat, String cinCandidat, Integer numTelCandidat, String adresseCandidat, Date dateNaissanceCandidat, String cv, String motivation) {
       this.idCandidat = idCandidat;
       this.nomPrenomCandidat = nomPrenomCandidat;
       this.cinCandidat = cinCandidat;
       this.numTelCandidat = numTelCandidat;
       this.adresseCandidat = adresseCandidat;
       this.dateNaissanceCandidat = dateNaissanceCandidat;
       this.cv = cv;
       this.motivation = motivation;
    }
   
     @Id 
@GeneratedValue(strategy = GenerationType.AUTO)

    
    @Column(name="id_candidat", unique=true, nullable=false)
    public int getIdCandidat() {
        return this.idCandidat;
    }
    
    public void setIdCandidat(int idCandidat) {
        this.idCandidat = idCandidat;
    }

    
    @Column(name="nom_prenom_candidat", length=150)
    public String getNomPrenomCandidat() {
        return this.nomPrenomCandidat;
    }
    
    public void setNomPrenomCandidat(String nomPrenomCandidat) {
        this.nomPrenomCandidat = nomPrenomCandidat;
    }

    
    @Column(name="cin_candidat", length=50)
    public String getCinCandidat() {
        return this.cinCandidat;
    }
    
    public void setCinCandidat(String cinCandidat) {
        this.cinCandidat = cinCandidat;
    }

    
    @Column(name="num_tel_candidat")
    public Integer getNumTelCandidat() {
        return this.numTelCandidat;
    }
    
    public void setNumTelCandidat(Integer numTelCandidat) {
        this.numTelCandidat = numTelCandidat;
    }

    
    @Column(name="adresse_candidat", length=350)
    public String getAdresseCandidat() {
        return this.adresseCandidat;
    }
    
    public void setAdresseCandidat(String adresseCandidat) {
        this.adresseCandidat = adresseCandidat;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_naissance_candidat", length=10)
    public Date getDateNaissanceCandidat() {
        return this.dateNaissanceCandidat;
    }
    
    public void setDateNaissanceCandidat(Date dateNaissanceCandidat) {
        this.dateNaissanceCandidat = dateNaissanceCandidat;
    }

    
    @Column(name="cv", length=550)
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }

    
    @Column(name="motivation", length=500)
    public String getMotivation() {
        return this.motivation;
    }
    
    public void setMotivation(String motivation) {
        this.motivation = motivation;
    }




}


