package model.pojo;
// Generated 22 juin 2016 15:27:10 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formation generated by hbm2java
 */
@Entity
@Table(name="formation"
    ,schema="dbo"
    ,catalog="Application_GRH"
)
public class Formation  implements java.io.Serializable {


     private int idFormation;
     private Formateur formateur;
     private Integer nombreHeure;
     private String domaine;
     private Date dateDebutFormation;
     private Date dateFinFormation;

    public Formation() {
    }

	
    public Formation(int idFormation) {
        this.idFormation = idFormation;
    }
    public Formation(int idFormation, Formateur formateur, Integer nombreHeure, String domaine, Date dateDebutFormation, Date dateFinFormation) {
       this.idFormation = idFormation;
       this.formateur = formateur;
       this.nombreHeure = nombreHeure;
       this.domaine = domaine;
       this.dateDebutFormation = dateDebutFormation;
       this.dateFinFormation = dateFinFormation;
    }
   
     @Id 
@GeneratedValue(strategy = GenerationType.AUTO)

    
    @Column(name="id_formation", unique=true, nullable=false)
    public int getIdFormation() {
        return this.idFormation;
    }
    
    public void setIdFormation(int idFormation) {
        this.idFormation = idFormation;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_formateur")
    public Formateur getFormateur() {
        return this.formateur;
    }
    
    public void setFormateur(Formateur formateur) {
        this.formateur = formateur;
    }

    
    @Column(name="nombre_heure")
    public Integer getNombreHeure() {
        return this.nombreHeure;
    }
    
    public void setNombreHeure(Integer nombreHeure) {
        this.nombreHeure = nombreHeure;
    }

    
    @Column(name="domaine", length=50)
    public String getDomaine() {
        return this.domaine;
    }
    
    public void setDomaine(String domaine) {
        this.domaine = domaine;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_debut_formation", length=10)
    public Date getDateDebutFormation() {
        return this.dateDebutFormation;
    }
    
    public void setDateDebutFormation(Date dateDebutFormation) {
        this.dateDebutFormation = dateDebutFormation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_fin_formation", length=10)
    public Date getDateFinFormation() {
        return this.dateFinFormation;
    }
    
    public void setDateFinFormation(Date dateFinFormation) {
        this.dateFinFormation = dateFinFormation;
    }




}


