package model.pojo;
// Generated 22 juin 2016 15:27:10 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HeureSupplementaire generated by hbm2java
 */
@Entity
@Table(name="heure_supplementaire"
    ,schema="dbo"
    ,catalog="Application_GRH"
)
public class HeureSupplementaire  implements java.io.Serializable {


     private int idHrSupp;
     private Personnel personnel;
     private Integer nombreHeureSupp;

    public HeureSupplementaire() {
    }

	
    public HeureSupplementaire(int idHrSupp) {
        this.idHrSupp = idHrSupp;
    }
    public HeureSupplementaire(int idHrSupp, Personnel personnel, Integer nombreHeureSupp) {
       this.idHrSupp = idHrSupp;
       this.personnel = personnel;
       this.nombreHeureSupp = nombreHeureSupp;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.AUTO)


    
    @Column(name="id_hr_supp", unique=true, nullable=false)
    public int getIdHrSupp() {
        return this.idHrSupp;
    }
    
    public void setIdHrSupp(int idHrSupp) {
        this.idHrSupp = idHrSupp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_personnel")
    public Personnel getPersonnel() {
        return this.personnel;
    }
    
    public void setPersonnel(Personnel personnel) {
        this.personnel = personnel;
    }

    
    @Column(name="nombre_heure_supp")
    public Integer getNombreHeureSupp() {
        return this.nombreHeureSupp;
    }
    
    public void setNombreHeureSupp(Integer nombreHeureSupp) {
        this.nombreHeureSupp = nombreHeureSupp;
    }




}


